language: ruby
rvm:
  - 1.9.3
  - 1.8.7
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION=">= 3.0.0"
notifications:
  email: false
gemfile: .gemfile
